### ISSUE TITLE
publish for Scala 2.13.0-RC3

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-swing#109]
@Sciss I happened to be on oss.sonatype.org and happened to notice a staging repo with some scala-swing artifacts for RC3. did you want those released?

I, and the rest of the Scala team, don't receive notifications when a staging repo is opened.

**Comment by Sciss** [comment]
Hey; yes, please, it should be fine to be released. Thanks

**Comment by SethTisue** [comment]
should be on its way to Maven Central now

**Comment by SethTisue** [comment]
* https://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.13.0-RC3/2.1.1/
* scala/make-release-notes@6bead50feb71787cb617aba5c1610ebbfa8f6578

**Comment by SethTisue** [comment]
2.13 artifacts are en route to Maven Central
