### ISSUE TITLE
Release for Dotty 3.0.0-M2

### ISSUE THREAD

**Issue by Sciss** [scala/scala-swing#144]
So I did [this](https://github.com/scala/scala-swing/commit/e03008bbb2e6b648c44199b081120d39a67fe781) and it made Travis publish for all Scala versions - https://travis-ci.com/github/scala/scala-swing/jobs/454325285 - , not just 3.0.0-M2. Should we rectify the scripts, or can you, @SethTisue , just delete the duplicate artifacts and release what's already on Sonatype?

**Comment by Sciss** [comment]
There used to be this https://github.com/scala/scala-swing/blob/693c8616e730ff22c198feb581b98d779fa7b426/build.sh#L26 - but that only worked for new 2.13.x versions.

**Comment by Sciss** [comment]
My attempt to fix the script: https://github.com/scala/scala-swing/pull/145

**Comment by Sciss** [comment]
I can't really test this, because travis-ci.org - non-paid service - has moved to throttle-ware, so it will take a day to build my fork. If you drop the current contents at sonatype, I will just merge this and keep fingers crossed.

**Comment by Sciss** [comment]
I think it works as expected. "Normal build", running each matrix cell with publish-local:

https://travis-ci.org/github/Sciss/scala-swing/builds/747665806

Tagged build, exiting all matrix cells except 2.13.x on JDK 8 with 'set every scala version':

https://travis-ci.org/github/Sciss/scala-swing/builds/747667211

Here is the one that tries to publish - it just publishes internally to Travis, but that's probably just the difference to your Travis set-up, credentials etc.:

https://travis-ci.org/github/Sciss/scala-swing/jobs/747667216

**Comment by SethTisue** [comment]
>  can you, @SethTisue , just delete the duplicate artifacts and release what's already on Sonatype?

done, a few minutes ago. (leaving the ticket open since the artifacts haven't actually reached Maven Central yet)

as for how to handle this going forward, see my remarks on #145

**Comment by SethTisue** [comment]
> I can't really test this, because travis-ci.org - non-paid service - has moved to throttle-ware, so it will take a day to build my fork

(as we discussed on Gitter, you can flip the switch to move your fork to travis-ci.com... though then your new problem will be running out of minutes)

**Comment by Sciss** [comment]
Ok - new artifacts should be ready to be released - https://travis-ci.com/github/scala/scala-swing/builds/206816837

**Comment by SethTisue** [comment]
I already released the staged artifacts from yesterday, and they are on Maven Central: https://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_3.0.0-M2/3.0.0/

Your attempt today went fine, I see the staging repo. So now you know the drill for next time.
