### ISSUE TITLE
JDK9 swing generification changes

### ISSUE THREAD

**Issue by andy1138** [scala/scala-swing#15]
Joseph Darcy (@jddarcy) has tweeted ( https://twitter.com/jddarcy/status/493137546814042112 )

_Swing developers, please recompile your apps with JDK 9 build 24 to test the compatibility of recent swing generification changes._

Guess this will need another branch (based on java7) with more changes.

**Comment by SethTisue** [comment]
@Sciss should this ticket remain open?

**Comment by Sciss** [comment]
With respect to the ticket's title; I can cross compile under JDK 11, so I would assume that there are no pending necessary changes regarding generification. In that sense I guess the ticket can be closed.

I would like to ask @jacobsallan if you are still interested in contributing your tutorials. That should go into a separate PR, however. I can see that you have extra branches in your fork; you could try to rebase them if necessary. There is an open ticket #68 regarding contributions, but last status was that it's still advisable to have the CLA signed. Perhaps @SethTisue could help identifying how to proceed there. I'm closing this issue now, so please for the tutorials open a new one or submit the PR directly.
