### ISSUE TITLE
Publish for Scala 3.0.0

### ISSUE THREAD

**Issue by tOverney** [scala/scala-swing#156]
Scala 3.0.0 got release last week;
Could we get the milestone version support bumped to 3.0.0 and released?

**Comment by Sciss** [comment]
scala-swing is already released for Scala 3.0.0: https://search.maven.org/artifact/org.scala-lang.modules/scala-swing_3/3.0.0/bundle

**Comment by tOverney** [comment]
I'm stupid, checked the releases and not even the closed issues... Very sorry about that!

Do you mind updating the description of the 3.0.0 release? https://github.com/scala/scala-swing/releases/tag/v3.0.0
