### ISSUE TITLE
which jdk version is adviced ?

### ISSUE THREAD

**Issue by devosalain** [scala/scala-swing#164]
I have openjdk versions 8,11,12,13,14,15,16,17 installed.
But which one would you advice to use ?

**Comment by Philippus** [comment]
I think you can follow this: https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

This library is tested on JDK 8, 11 and 17: https://github.com/scala/scala-swing/blob/work/.github/workflows/ci.yml#L13
