### ISSUE TITLE
API documentation links to 404

### ISSUE THREAD

**Issue by rusty-snake** [scala/scala-swing#167]
> The API documentation for scala-swing can be found at http://www.scala-lang.org/documentation/api.html.

> Not found.

**Comment by SethTisue** [comment]
A PR replacing this with a link to javadoc.io (a site that publishes Scaladoc/Javadoc for anything on Maven Central) would be welcome.

**Comment by Sciss** [comment]
that would be https://javadoc.io/doc/org.scala-lang.modules/scala-swing_2.13/latest/index.html or https://javadoc.io/doc/org.scala-lang.modules/scala-swing_3/latest/index.html
