### ISSUE TITLE
Add support for smallIcon property in Action and use it in MenuItem constructors

### ISSUE THREAD

**Issue by jacobsallan** [scala/scala-swing#32]
javax.swing.Action (http://docs.oracle.com/javase/7/docs/api/javax/swing/Action.html ) uses two keys to set the icon property of the components that are constructed with Action instances.  The two are LARGE_ICON_KEY and SMALL_ICON.  The LARGE_ICON_KEY is used to set the icon property of most Swing components that are AbstractButtons except for MenuItems.  The SMALL_ICON property applies when the Action is used to construct MenuItems.

scala.swing.Action should have defs for smallIcon.  The MenuItem constructor that takes an Action argument should assign MenuItem icon with the value from Action.smallIcon.

The existing icon defs in scala.swing.Action can remain unchanged.

**Comment by Sciss** [comment]
`var smallIcon` has been introduced already a while ago. Closing.
