### ISSUE TITLE
Creating a release from a tag 

### ISSUE THREAD

**Issue by andy1138** [scala/scala-swing#37]
Hi @adriaanm 

Following on from #33 

I'm trying to get a tagged release (tag: v2.0.0-M2) of the java7 branch onto sonatype/maven.com however, as you may guess, its not arriving. I'm copied all your changes to 'master' to the 'java7' branch, hopefully successfully :-) 

I'm 
- tagging a build (tag: v2.0.0-M2), 
- its then running a Travis (https://travis-ci.org/scala/scala-swing/builds/49170670) 
- and I'm expecting it to arrive at (http://search.maven.org/#browse%7C-328986604 )

Do you know what I'm doing wrong or who to talk to
Thanks
Andy

**Comment by andy1138** [comment]
Hi @adriaanm 
forget above, just found it at 
https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/modules/scala-swing_2.11/

the snapshot being the name in the build.sbt file.

How do you change the version name from '-SNAPSHOT' to '-M2' in build.sbt. ?
Do you do a commit/wait for build/and rest back to 'SNAPSHOT'.  Or do a branch  called 'milestone 2' and change that and do a build (possibly deleting branch afterwards).  Or some other way.

**Comment by adriaanm** [comment]
The version should be set by the script when a tag triggers a build, as in here: https://travis-ci.org/scala/scala-swing/jobs/49170671. Looking into why it didn't publish.

**Comment by adriaanm** [comment]
It won't arrive directly on maven central, though. That's where one of the core team members come in. We have to promote the staging repo on sonatype to be released to maven central.

**Comment by adriaanm** [comment]
Actually, it did decide to release: https://travis-ci.org/scala/scala-swing/jobs/49170671#L126
```
Going to release from tag v2.0.0-M2!
```

**Comment by adriaanm** [comment]
Ah, the build [has gone multi-project](https://github.com/scala/scala-swing/blob/v2.0.0-M2/build.sbt#L37). The [scala module build plugin](https://github.com/scala/sbt-scala-modules) was not designed for that setup, but it can probably be made to work. I think you need to adjust your build and admin/build.sh so that it sets the version etc correctly. 

For one, I believe [scalaModuleSettings](https://github.com/scala/scala-swing/blob/v2.0.0-M2/build.sbt#L3) on line 3 should be added to your [project's settings](https://github.com/scala/scala-swing/blob/v2.0.0-M2/build.sbt#L37) on line 37 if you define one explicitly, instead of sitting at the top-level.

You should be able to experiment with this by invoking the admin/build.sh script, setting the variables tested on [line 8](https://github.com/scala/scala-swing/blob/master/admin/build.sh#L8) (TRAVIS_JDK_VERSION="openjdk7", TRAVIS_TAG="v2.0.0-TST").

Maybe one of our sbt gurus, Set(@gkossakowski, @eed3si9n, @jsuereth, @retronym) can offer some more concrete advice.

**Comment by andy1138** [comment]
Thanks @adriaanm for looking at this.

The idea of the multi-project was to keep anything that would stop the build running on headless servers away from anything that will require a physical screen. It may just be easier to create a separate build.sbt  within the sub-projects and put the root build.sbt back to a single project.

**Comment by gkossakowski** [comment]
I'll have to recal what the plugin does to offer some specific advice. I'll have a look some time this week.

**Comment by andy1138** [comment]
Hi @gkossakowski , thanks for the help. I'm happy to split it into separate build.sbt files if it turns into a lot of work.

**Comment by gkossakowski** [comment]
@andy1138, if it's easy for you to do the split then please go ahead with this idea. Figuring out what's wrong with the plugin would take quiet a bit of work.

In meantime, I created a placeholder issue scala/sbt-scala-modules#8 for the problem discovered here so it won't be forgotten.

**Comment by andy1138** [comment]
@adriaanm @gkossakowski  
I've managed to get the tagged release working :-)
I found this https://github.com/sbt/sbt/issues/1430 and so updated the version of sbt to 0.13.7 and I now thinks it has stagged ( see https://travis-ci.org/scala/scala-swing/jobs/49492878 ), called scala-swing_2.11-2.0.0-M1 . 
If I'm correct then this is where one of you need to promote it.

**Comment by adriaanm** [comment]
Excellent! I've close the staging repo and can promote once you confirm it looks good. 

So, could you double check that https://oss.sonatype.org/content/repositories/orgscala-lang-1172/org/scala-lang/modules/scala-swing_2.11/2.0.0-M1/ contains what you'd expect it to?

**Comment by adriaanm** [comment]
Using https://github.com/adriaanm/binfu/blob/master/sonafu.sh and the sonatype credentials, this is the flow, for the record:

```
➜  ~  st_stagingRepoList 
{
  "transitioning": false,
  "notifications": 0,
  "releaseRepositoryName": "Releases",
  "releaseRepositoryId": "releases",
  "provider": "maven2",
  "description": "Implicitly created (auto staging).",
  "userAgent": "Apache Ivy/2.3.0-sbt-fccfbd44c9f64523b61398a0155784dcbaeae28f",
  "userId": "lamp",
  "policy": "release",
  "type": "open",
  "repositoryId": "orgscala-lang-1172",
  "profileType": "repository",
  "profileName": "org.scala-lang",
  "profileId": "1d58d199afe0a",
  "ipAddress": "199.182.121.63",
  "repositoryURI": "https://oss.sonatype.org/content/repositories/orgscala-lang-1172",
  "created": "2015-02-04T12:28:09.109-06:00",
  "createdDate": "Wed Feb 04 12:28:09 CST 2015",
  "createdTimestamp": 1423074489109,
  "updated": "2015-02-04T12:28:12.390-06:00",
  "updatedDate": "Wed Feb 04 12:28:12 CST 2015",
  "updatedTimestamp": 1423074492390
}
➜  ~  st_stagingRepoClose orgscala-lang-1172
➜  ~  # pending confirmation: st_stagingRepoPromote orgscala-lang-1172
```

**Comment by andy1138** [comment]
LGTM 

I'll fill in scala/sbt-scala-modules#8 with some details.

Thanks for the help.

**Comment by adriaanm** [comment]
Done! Congrats on the first milestone!
