### ISSUE TITLE
Milestone build for both scala-2.10 and 2.11 (scala-swing-M2)

### ISSUE THREAD

**Issue by andy1138** [scala/scala-swing#40]
Hi @adriaanm  (/cc @fommil )
I've been asked for a scala-2.10 version so I've managed to change the build (it was only the addition to .travis.yml of scala-2.10) but that means that I need to inc the milestone number to M2 (M1 was good practice :-) ) 

The travis build look ok but I cannot see the sonatype destinations (asks for login ) but I think that is something on your side, can you check and do your thing.

Thanks 

Travis 2.10 job: https://travis-ci.org/scala/scala-swing/jobs/50086905
Travis 2.11 job: https://travis-ci.org/scala/scala-swing/jobs/50086903

**Comment by fommil** [comment]
cool, now you just have to click the buttons on sonatype and then we wait for central to catch up.

It only took over a year, and, of course, you had to do this the **day** I finally beat our custom build tool with a big stick and upgraded to 2.11. :stuck_out_tongue:

**Comment by andy1138** [comment]
@fommil  So now you get to use all the new shiny feature of 2.11, big win  :-)

**Comment by fommil** [comment]
@andy1138 not working yet. got our own build tool.

**Comment by adriaanm** [comment]
Getting the hang of it, @andy1138! 

I closed staging repos https://oss.sonatype.org/content/repositories/orgscala-lang-1180 and https://oss.sonatype.org/content/repositories/orgscala-lang-1181 -- please double check their contents and confirm, so I can promote them to maven central.

**Comment by andy1138** [comment]
Thanks @adriaanm 
LGTM 
and hopefully this is the last one for a while

**Comment by adriaanm** [comment]
Cool! Promoting now. Thanks for keeping the release train running smoothly!

**Comment by fommil** [comment]
:smile:
