### ISSUE TITLE
community: open issues here for any significant old issue from JIRA

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-swing#48]
today I closed the following scala-swing tickets in the [Scala JIRA instance](https://issues.scala-lang.org):
8495, 7827, 7742, 7738, 7597, 7309, 7307, 5701, 5616, 5492, 5381, 4998, 4905, 4904, 4903, 4823, 4078, 3933, 3823, 3557, 3335, 3319, 3259, 2362, 2154, 2069, 1824, 1613

many of these ought to become issues here in this repo on GitHub. interested community members are invited to open new issues for them here, with links in both directions

**Comment by Sciss** [comment]
Are those tickets still visible somewhere - https://issues.scala-lang.org/browse/8495 etc. doesn't work any longer

**Comment by SethTisue** [comment]
* https://issues.scala-lang.org/browse/SI-1613
* https://issues.scala-lang.org/browse/SI-1824
* https://issues.scala-lang.org/browse/SI-2069
* https://issues.scala-lang.org/browse/SI-2154
* https://issues.scala-lang.org/browse/SI-2362
* https://issues.scala-lang.org/browse/SI-3259
* https://issues.scala-lang.org/browse/SI-3319
* https://issues.scala-lang.org/browse/SI-3335
* https://issues.scala-lang.org/browse/SI-3557
* https://issues.scala-lang.org/browse/SI-3823
* https://issues.scala-lang.org/browse/SI-3933
* https://issues.scala-lang.org/browse/SI-4078
* https://issues.scala-lang.org/browse/SI-4823
* https://issues.scala-lang.org/browse/SI-4903
* https://issues.scala-lang.org/browse/SI-4904
* https://issues.scala-lang.org/browse/SI-4905
* https://issues.scala-lang.org/browse/SI-4998
* https://issues.scala-lang.org/browse/SI-5381
* https://issues.scala-lang.org/browse/SI-5492
* https://issues.scala-lang.org/browse/SI-5616
* https://issues.scala-lang.org/browse/SI-5701
* https://issues.scala-lang.org/browse/SI-7307
* https://issues.scala-lang.org/browse/SI-7309
* https://issues.scala-lang.org/browse/SI-7597
* https://issues.scala-lang.org/browse/SI-7738
* https://issues.scala-lang.org/browse/SI-7742
* https://issues.scala-lang.org/browse/SI-7827
* https://issues.scala-lang.org/browse/SI-8495

**Comment by Sciss** [comment]
I'm trying to sort out the invalid issues first.

# SI-2069 MainFrame close function doesn't exit app

invalid / won't fix (see original comment).

# SI-4905 Swing PopupMenu class

This issue has been fixed.

# SI-7307 scala.swing.TextField.reactions suppresses all the keyboard events

The reporter missed to enable key events via `listenTo(keys)`.

# SI-7309 scala.swing.BorderPane.reactions suppresses FocusGained

The reporter missed to subscribe to the panel and/or enable focusability. Using `listenTo(panel1)` and `panel1.focusable = true` shows that it works.

# SI-7597 Can't show a FileChooser over a Frame or a Dialog

Invalid / works-for-me

**Comment by Sciss** [comment]
Fixed in https://github.com/scala/scala-swing/pull/75:

### SI-4823 Swing Table sorting doesn't map row index from view to model correctly

**Comment by Sciss** [comment]
SI-4903 is recreated as #97

**Comment by Sciss** [comment]
### SI-5381 scala.swing.TabbedPane.pages does not store its sub pages

I would judge as "out of scope". If someone wants to address this with a PR, fine. Definitely I would not consider it a bug.

**Comment by Sciss** [comment]
### SI-5492 Missing EditDone event from TextArea

I think it's not a such a good match; text components are traced using `ValueChanged` based on document changes, also there is no equivalent to the action-listener of text field. If the behaviour is needed, it's very easy to listen for `FocusLost` instead. So marking as won't fix.

**Comment by Sciss** [comment]
### SI-5701 EditorPane problem with text/html -- contents is blank/OK based on how assigned to 'text'

Marking as invalid. The "bug" example given does not work, because `text += x` is `text = text + x`, and the initial text after setting to contentType html is a html document (`<html><head> </head> <body> ... </body> </html>`), so you're appending after the end of the body.

**Comment by Sciss** [comment]
SI-7742 ListView.selection.indices has few methods

Marking as invalid. For example, poster says "is even impossible to get the individual index values". This is not true; for example you can say `println(list.selection.indices.mkString(", "))`; it behaves like a normal set.

**Comment by Sciss** [comment]
### SI-3259 Swing's SuperMixing enhancement

Marking as won't fix / too broad. There are already workarounds, for example you can call `preferredSize_=` to provide a user-defined size. You can already override `paintComponent`, and arguably overriding `setBounds` or `getBounds` is not a good idea. New issues should be opened instead for specific missing methods.

**Comment by Sciss** [comment]
As far as I can see, that leaves the following issues valid/open:

- SI-1613 scala.swing.ComboBox should support mutable item lists 
- SI-2154 scala.swing.ComboBox should have a method for changing the items
- SI-2362 scala.swing.Menu contents field permanently empty
- SI-3319 Missing GroupPanel
- SI-3335 scala.swing.Window.contents_=() should not call pack()
- SI-3557 Swing TextAction
- SI-3823 scala.swing.Scrollable does not implement javax.swing.Scrollable in peer
- SI-3933 Request for a scala.swing.CardPanel (uses javax.swing.CardLayout)
- SI-4078 GridBagPanel is inflexible
- SI-4904 Component/Publisher initialization may be broken -- or is somewhat obscure
- SI-4998 No Events Published from ListModel for ListView 
- SI-5616 Incorrect CellEditor for Table when column is null
- SI-7827 Missing the property iconImages in RichWindow
- SI-8495 swing.Publisher does not always notify all listeners

Note re 1613, 2154, 3319: improved ComboBox and a GroupPanel are part of my SwingPlus library. It would be good to clean them up and integrate them in scala-swing at some point.

**Comment by SethTisue** [comment]
now that GitHub allows issues to be relocated within the same organization, it would be possible to simply move those tickets here. @Sciss does your level of access in the scala org permit you to do that? if not, would you like me to do it?

**Comment by Sciss** [comment]
No, I don't have admin rights for those issues (I don't see the 'Lock conversation', 'Pin issue' 'Transfer issue', 'Delete issue' buttons below participants).

**Comment by SethTisue** [comment]
issues on your [list](https://github.com/scala/scala-swing/issues/48#issuecomment-481806078), transferred and reopened!
