### ISSUE TITLE
retire scala-swing Google Group and remove from readme

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-swing#52]
no traffic in a long time — I don't think the library needs a dedicated group

**Comment by SethTisue** [comment]
@benhutchison wdyt?

**Comment by benhutchison** [comment]
Oops, missed this. Agree.

**Comment by SethTisue** [comment]
as for actually shutting down the group, I used https://groups.google.com/forum/#!contactowner/scala-swing to send an email to whoever owns the group, I don't know who that is, and I don't see any other way to find out

**Comment by SethTisue** [comment]
keeping the issue open until we can actually get the group shut down

**Comment by SethTisue** [comment]
@fsalvi @cunei are you perhaps managers or owners of the group?

**Comment by cunei** [comment]
@SethTisue Google tells me: "There is no group named scala-swing". I've never been subscribed, so I don't know where it lived. Did you delete the group, and if so, did you download an archive before deleting it?

**Comment by SethTisue** [comment]
interesting. I didn't delete it, but it's gone. not sure what happened there. I don't have an archive, no. but there wasn't much to save, anyway.

so, we're done, then.
