### ISSUE TITLE
publish for Scala 2.13.0-M2?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-swing#65]
and once available, add to https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md

**Comment by SethTisue** [comment]
@benhutchison are you able to take this on...?

**Comment by benhutchison** [comment]
Yes, I'll have some time to look at it today

**Comment by benhutchison** [comment]
@SethTisue As its my first time doing a swing release via github tag, can you please review before I publish tag: https://github.com/scala/scala-swing/releases/tag/untagged-5bbb87e29549f27b4329

**Comment by lrytz** [comment]
@benhutchison it seems your draft would tag the current 2.0.x, which has moved ahead of 2.0.0, so I guess you'd better do a full 2.0.1 in this case.

Just tagging the 2.0.0 revision (76e4ffc9e8b8ebf22fc176e3ab6a5a6b1268fb81) won't work because it's missing some infrastructure. For `v2.0.0#2.13.0-M1`, I cherry-picked the infra change on top of 2.0.0 and tagged that. So you could use the same revision (ce14150179d62788024b9957be43d3e1ff085cd7) for `v2.0.0#2.13.0-M2`, that should work.

**Comment by benhutchison** [comment]
Ok, please be patient -  this is new to me and so Im going slowly rather
than make a mistake.

I wasn't able to create a release off commit ce14150
<https://github.com/scala/scala-swing/commit/ce14150179d62788024b9957be43d3e1ff085cd7>
in
the github UI, AFAICT it doesn't consider that SHA a "recent commit" any
more.

Alternately, I created a draft v2.0.1 release which should build against
2.13 M2. Im not certain about the `version` in build.sbt, its still got a
SNAPSHOT suffix, that seems to be intended and the github release number
overrides it.?

**Comment by benhutchison** [comment]
The draft 2.0.1:
https://github.com/scala/scala-swing/releases/tag/untagged-1158048b2b76a89aeab4

**Comment by SethTisue** [comment]
> Im not certain about the `version` in build.sbt, its still got a
> SNAPSHOT suffix, that seems to be intended and the github release number
> overrides it.

correct

in your draft release, the tag name is `v2.0.1#2.13.0-M2`, but I think it should just be `v2.0.1`. the `#` thing is only needed when republishing an already-published library version for a new Scala version. the default behavior is to publish for all of the supported Scala versions — which is what we want here, for 2.0.1 to be a real release

**Comment by benhutchison** [comment]
Ok, Ive published a release v2.0.1 and travis build OK.

In the release instructions it says "Log into https://oss.sonatype.org/ and
identify the staging repository"

The only credentials Ive got for sonatype are my personal creds, and I cant
find a scala-swing staging repo using those.

-Ben

**Comment by SethTisue** [comment]
the Scala team pulls the final lever here using our org-wide credentials.

I hit "Close" followed by "Release" in the Sonatype web UI just now, so the artifacts should be on their way to Maven Central.

**Comment by benhutchison** [comment]
Thanks. release notes repo has a PR for this now.

**Comment by SethTisue** [comment]
looks like we're done! thanks Ben!
