### ISSUE TITLE
release for Scala 2.13.0-M3, please?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-swing#70]

**Comment by benhutchison** [comment]
v2.0.2 release and staged. 

The new tag-based artifact publishing is awesome once you get used to it; great work guys!

**Comment by SethTisue** [comment]
http://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.13.0-M3/2.0.2/
scala/make-release-notes@f03a79fa622868cf97ad74589e21b77279cbef8b
👍
