### ISSUE TITLE
Sciss take role as a maintainer?

### ISSUE THREAD

**Issue by benhutchison** [scala/scala-swing#76]
@Sciss you are our most prolific contributor and probably know the codebase better than anyone. Would you be interested in joining as a maintainer?

**Comment by Sciss** [comment]
Pff, ahhh - what does that exactly involve? ;_)

**Comment by benhutchison** [comment]
Swing is in maintenance mode, so basically: Reviewing PRs and Issues, periodic releases for ecosystem changes like Scala updates.

Relative to present, it would empower you to get releases out potentially quicker than waiting for my split attention to come around to Scala swing.

**Comment by Sciss** [comment]
Ok. But I'll have to learn about the release process. I guess there is a document or guide or wiki?

**Comment by benhutchison** [comment]
Ah... there is this: https://github.com/scala/sbt-scala-module/issues/16

The release process is actually a very cool  automated tag based system. Seth does the last step, push to maven.

Also, prolly need to get an OK from @SethTisue to add you as maintainer..

**Comment by Sciss** [comment]
Ok, thanks

**Comment by SethTisue** [comment]
👍. PR the readme change? is it time to remove @andy1138, have we not heard from him in a while...?

**Comment by SethTisue** [comment]
@Sciss I've added you to https://github.com/orgs/scala/teams/community-maintainers/members

**Comment by Sciss** [comment]
Another question - someone needs to review my pull requests, right? So I should push changes to my fork, open a pull request, and somebody gives green light, or how does it work before I merge?

**Comment by SethTisue** [comment]
you don't need approval from me or the Scala team to merge stuff, you and Ben should do as you see fit, in consultation with the user community.

as of Scala 2.13, scala-swing will no longer be bundled with Scala as of Scala 2.13.

but, it is still in the `scala._` namespace and published under the `org.scala-lang.modules` organization, so it still has _some_ identification with Lightbend and the Scala Center. so if any radical changes are planned, we'd like to be consulted about whether it makes sense to continue under the existing namespace and organization, or go fully third-party. the best people to consult on that would be the Scala Platform Process committee, I think.

another thing to consider is the Swing example in the Odersky, Venners, and Spoon book. if the library goes in a direction where that example no longer works (well small tweaks, is okay), that would also be something we'd want to try and manage appropriately.

but for ordinary changes, no worries.

**Comment by Sciss** [comment]
Ok. What's the difference in 2.13 versus 2.12? Hasn't Swing been in `org.scala-lang.modules` already for a while?

I don't plan any radical changes; basically migrating some additions from swing-plus (missing API, missing widgets), fixing perhaps a few issues.

**Comment by SethTisue** [comment]
> What's the difference in 2.13 versus 2.12

whether distribution packages downloaded from scala-lang.org have a copy of the JAR in the `lib` directory or not (which makes it available by default in the REPL)

```
% ls /usr/local/scala-2.12.6/lib
jline-2.14.6.jar                         scala-reflect.jar
scala-compiler.jar                       scala-swing_2.12-2.0.0.jar
scala-library.jar                        scala-xml_2.12-1.0.6.jar
scala-parser-combinators_2.12-1.0.7.jar  scalap-2.12.6.jar
% /usr/local/scala-2.12.6/bin/scala
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> new scala.swing.Frame
res1: scala.swing.Frame = scala.swing.Frame$$anon$1[...]
```

but:

```
~ % ls /usr/local/scala-2.13.0-M3/lib                                                                       (master|✔)
jline-2.14.5.jar               scala-library.jar              scala-xml_2.13.0-M3-1.0.6.jar
scala-compiler.jar             scala-reflect.jar              scalap-2.13.0-M3.jar
~ % /usr/local/scala-2.13.0-M3/bin/scala                                                                    (master|✔)
Welcome to Scala 2.13.0-M3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> new scala.swing.Frame
                 ^
       error: object swing is not a member of package scala
```

since most people use IntelliJ or sbt (or whatever) instead of using downloaded distributions, it's less and less relevant these days whether something is bundled in our distribution packages or not.

**Comment by Sciss** [comment]
I see, thank you.

Regarding the **book examples**, the best would probably be to simply drop them into test sources, so we would automatically detect if there is a deviation introduced. I have printed copy of edition 2 somewhere buried, and the PDF of edition 1; could you perhaps - if you have PDF of the latest edition - just send me the code examples, then I can add them. In the version I'm seeing, that's listings 32.1 through 32.4, 33.1 through 33.9 ; or if they've never changed, I can copy them from my sources.

**Comment by SethTisue** [comment]
opened #77 on it.

**Comment by benhutchison** [comment]
Just a quick note to say Im still around, willing and able to maintain Scala Swing. As Im no longer using Swing at all myself, I hope @Sciss will continue the excellent job he's done leading Scala Swing maintenance these last 2 years. However I can serve as a fallback should he be unavailable or need assistance.
