### ISSUE TITLE
1.0.x branch (inadvertently?) dropped support for Java 6 & 7 and Scala 2.10

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-swing#79]
it came up over at https://github.com/scala/sbt-scala-module/issues/32 that @Sciss thought scala-swing was built on Java 6. I thought it was too, and the repo readme here claims it is.

but it isn't. it was, but at some point, it changed, perhaps inadvertently. I looks to me like changes were made on the 1.0.x branch that should probably only been made on 2.0.x. this included building on JDK 8 only and also dropping support for Scala 2.10, which the readme also claims 1.0.x supports.

as for the related sbt version issue:
* I think it's fine for 1.0.x to stay on 0.13.x indefinitely
* for 2.0.x to move to sbt 1, it would have to drop JDK 6 and 7 support. @Sciss indicated a desire to keep supporting JDK 6 and 7, but I'm not sure if he cares about that on 2.0.x too, or whether keeping the support on the 1.0.x branch is enough. (@Sciss, if you decide 2.0.x should stay on sbt 0.13, that's fine w/ me.)

**Comment by Sciss** [comment]
Oh well, I can't even install OpenJDK 6 on Debian Stretch without major hassle. So I actually won't be able to compile on JDK 6 any more, anyways. And thus, no objection changing to sbt 1.x for Swing 2.0.x

**Comment by SethTisue** [comment]
okay, cool!
