### ISSUE TITLE
Scala 2.13.0(-M5) support

### ISSUE THREAD

**Issue by Sciss** [scala/scala-swing#84]
We need some help getting this done. As Scala Swing heavily relies on the collections API, I assume this is not a trivial task. Opening this issue as a point of contact.

**Comment by som-snytt** [comment]
I'm spending a few minutes with this. It looks like one problem is that imports are used incorrectly, but the compiler bug was fixed.

**Comment by Sciss** [comment]
Ok great. I was mainly thinking about things like these:

https://github.com/scala/scala-swing/blob/2.0.x/src/main/scala/scala/swing/BufferWrapper.scala

But perhaps I'm wrong and this already compiles correctly most of the time.

**Comment by som-snytt** [comment]
`Seq` changed, and also some imports collided because of naming.

**Comment by som-snytt** [comment]
@Sciss I updated.  I found my old scala-swing app from 2011, but I couldn't build it against 2.9 anymore. I was about to try it out against the revision on 2.13... I may need another coffee.

**Comment by SethTisue** [comment]
* https://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.13.0-M5/2.1.0/
* scala/make-release-notes@549b92157e78aa497fbda330dd858379296d2403
