### ISSUE TITLE
relicense under Apache 2.0

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-swing#90]
just like e.g. https://github.com/scala/scala-xml/pull/242 and https://github.com/scala/scala-parser-combinators/pull/184

**Comment by Sciss** [comment]
Note that his probably needs a change in defaults: https://github.com/scala/sbt-scala-module/blob/7aee2b537d30f227f2bb27ac6b1c09d5e94dcdf1/src/main/scala/ScalaModulePlugin.scala#L130

**Comment by SethTisue** [comment]
ah, good catch. I opened https://github.com/scala/sbt-scala-module/issues/48 on it

**Comment by SethTisue** [comment]
in the meantime, we can

```diff
+    // this line could be removed after https://github.com/scala/sbt-scala-module/issues/48 is fixed
+    licenses := Seq(("Apache-2.0", url("https://www.apache.org/licenses/LICENSE-2.0"))),
```
